version: '3.7'

services:

  rancher:
    image: rancher/rancher
    restart: always
    privileged: true
    volumes:
      - ~/rancher:/var/lib/rancher
#      - ~/SSL:/etc/rancher/ssl
    ports:
      - 80:80
      - 443:443
#    command: --no-cacerts

#networks:
#  default: 
#    name: front
